### PR TITLE
Final version

### PR DESCRIPTION
**Pull request by prokop7**

### CODE REVIEW

**Review by kos33rd — APPROVED** [review]
👍

**Comment by alikhil** [comment]
Hey guys, I am going to use this project as a base for Advanced JS course project.

**Comment by kevinkhanda** [comment]
That's great!
Maybe you will also make some improvements and add features?
I can name some of them

**Comment by kevinkhanda** [comment]
Also check this
screenshot 2019-01-31 at 17 34 22

**Comment by Raiondesu** [comment]
@KKhanda, this is related to an outdated version of webpack-dev-server. Nothing critical. I dismissed it as "vulnerable code is not actually used".

**Pull request merged**
